#!/bin/bash
#
# addcharge - calcula e adiciona cargas à moleculas
#
# Site   : http://napolie.far.ufba.br
# Autores: Pedro Sousa Lacerda <kanvuanza@gmail.com>
#          Humberto Freitas <humbarato@gmail.com>
#
# -----------------------------------------------------------------------------
# Este programa calcula e adiciona cargas à moleculas usando a metodologia tal,
# bla, bah.
#
# Sinopse:
#   addcharge INPUT [OUTPUT]
#   addcharge --batch PATTERN OUTDIR
#
# Uso:
#   Quando apenas o parâmetro INPUT é passado, nome do arquivo de saída tem o
#   sufixo '-charged' adicionado logo antes da extensão. Por exemplo se INPUT
#   for 'ligand.mol2', a saída OUTPUT será 'ligand-charged.mol2'.
#
#   Quando ambos INPUT e OUTPUT são passados, o arquivo de entrada e saída
#   recebem seus nomes, respectivamente.
#
#   A flag --batch indica que todos os arquivos que casam com o padrão PATTERN
#   serão convertidos e salvos no diretório OUTDIR.
#
# Exemplos:
#   $ addcharge ar75.mol2
#   $ addcharge ar01.mol2 ar01-c.mol2
#   $ addcharge --batch /inputs/*.mol2 /outputs
# -----------------------------------------------------------------------------
#

function usage {
    echo "Usage: $0 INPUT [OUTPUT]"
    echo "       $0 --batch PATTERN OUTDIR"
}

if [[ $# > 3 ]];
    usage
    exit 1
fi

case $# in
    1)
        FORMAT="${1##*.}"
        INPUT="$1"
        OUTPUT="${1%.*}-charged.$FORMAT"
        ;;
    2)
        FORMAT="${1##*.}"
        INPUT="$1"
        OUTPUT="$2"
        ;;
    3)
        
;
for arg in "$@"
do
    case "$arg" in
        --batch)
            BATCH=1
            PATTERN="$1"
            OUTDIR="$2"
        *)
            which $0




# Descomente para auxiliar na depuração.
set -eux

BATCH=0
INPUT=
OUTPUT=
PATTERN=
OUTDIR=



if [[ $# != 1 ]];
then
    echo "    Uso: $0 /diretorio/contendo/mol2/"
    exit 1
fi

DIR="$1" # diretório contendo arquivos mol2


for MOL2 in $DIR/*.mol2;
do
    LIGAND=`basename $MOL2 .mol2`
    echo "Calculando cargas de $LIGAND..."
    MOPAC_KEYWORDS="PM7 1SCF XYZ NOINTER SCALE=1.4 NSURF=2 SCINCR=0.4 NOMM CHARGE=0 AUX"
    
    # Converte mol2 em mop, adiciona as keywords do MOPAC e sobrescreve o arquivo mop.
    babel -imol2 $LIGAND.mol2 -omop 2> /dev/null      \
        | sed "s/PUT KEYWORDS HERE/$MOPAC_KEYWORDS/g" \
        > $LIGAND.mop

    /opt/mopac/MOPAC2012.exe $LIGAND.mop 2> /dev/null
    babel -imoo $LIGAND.out -omol2 $LIGAND-charged.mol2 2> /dev/null
done
