#!/bin/bash
#
# addcharge - calcula e adiciona cargas a uma molécula
#
# Site   : http://napolie.far.ufba.br
# Autores: Pedro Sousa Lacerda <kanvuanza@gmail.com>
#          Humberto Freitas <humbarato@gmail.com>
#
# -----------------------------------------------------------------------------
# Este programa calcula e adiciona cargas à moleculas usando a metodologia tal,
# bla, bah.
#
# Sinopse:
#   addcharge INFILE MOPAC_KEYWORDS
#
# Uso:
#   Quando apenas o parâmetro INPUT é passado, nome do arquivo de saída tem o
#   sufixo '-charged' adicionado logo antes da extensão. Por exemplo se INPUT
#   for 'ligand.mol2', a saída OUTPUT será 'ligand-charged.mol2'.
#
#   Quando ambos INPUT e OUTPUT são passados, o arquivo de entrada e saída
#   recebem seus nomes, respectivamente.
#
# Exemplos:
#   $ addcharge ar75.mol2
#   $ addcharge ar01.mol2 ar01-c.mol2
# -----------------------------------------------------------------------------
#

#set -eux

source helpers.sh

##
# Checa número de argumentos
#
[[ $# != 2 ]] && usage && exit 1


##
# Declaração de variáveis
#
declare -r IFILE="$1"                       # input file
declare -r KEYWORDS="$2"                    # MOPAC keywords
declare -r LIGAND=`basename "$IFILE" .mol2` # nome do ligante
declare -r WORKSPACE=`mktemp -d`            # onde salvar arquivos temporários


##
# Checa o arquivo de entrada
#
[[ ! -r "$IFILE" || ! -f "$IFILE" ]] && 
    error "Não possível ler o conteúdo de \"$IFILE\"."


put green "Sucesso!"
exit 0

## 
# Converte o arquivo de entrada *.mol2 em *.mop
#
babel -imol2 "$IFILE" -omop 2> /dev/null      \
    | sed "s/PUT KEYWORDS HERE/$KEYWORDS/g"   \
    > "$WORKSPACE/$LIGAND.mop"


##
# Computa cargas do *.mop e as salva, junto com as posições, em *.out
#
mopac "$WORKSPACE/$LIGAND.mop" 2> /dev/null


##
# Converte o *.out no formato mol2 e exibe o conteúdo na STDOUT
#
babel -imoo "$WORKSPACE/$LIGAND.out" -omol2 2> /dev/null

