#!/bin/bash
#
# vscreening - triagem virtual com o Autodock Vina
#
# Site : http://napolie.far.ufba.br
# Autor: Pedro Sousa Lacerda <kanvuanza@gmail.com>
#
#------------------------------------------------------------------------------
#
# Sinopse
#   vscreening -c CONFIG -i INDIR [-o OUTDIR]
#
#

source helpers.sh

##
# Recebe parâmetros
#
eval set -- `options 'vc:i:o:' 'verbose,config:,indir:outdir:' "$@"`

declare INDIR CONFIG VERBOSE=0

while true; do
    case "$1" in
        -v|--verbose) VERBOSE=1 ; shift ;;
        -c|--config) CONFIG="$2" ; shift 2 ;;
        -i|--indir) INDIR="$2" ; shift 2 ;;
        -o|--outdir) OUTDIR="$2" ; shift 2 ;;
        --) shift ; break ;;
        *) usage ; exit 1 ;;
    esac
done

##
# Valida parâmetros
#
test ! -d "$INDIR" -o ! -r "$INDIR" &&
    die "\"$INDIR\" não é um diretório ou não é possível lê-lo."

test ! -d "$OUTDIR" -o ! -w "$OUTDIR" &&
    die "\"$OUTDIR\" não é um diretório ou não é possível escrevê-lo."

test ! -f "$CONFIG" -o ! -r "$CONFIG" &&
    die "Não é possível ler \"$CONFIG\"."

##
# Itera sobre todos os arquivos
#
for IFILE in "$INDIR"/*.pdbqt
do
    LIGAND=`basename "$file" .pdbqt` # nome do ligante
    OFILE="$OUTDIR/$LIGAND.out"      # arquivo de saída
    LFILE="$OUTDIR/$LIGAND.log"      # arquivo de log
    
    vina -c "$CONFIG" -i "$IFILE" -o "$OFILE" -l "$LFILE"

    mv $.

done




